sudo: false
language: java
jdk:
  - oraclejdk8

before_install:
    - curl https://raw.githubusercontent.com/s4u/parent/travis/settings.xml -o ../settings.xml
    - ./set_github_ssh_key.sh
    - ./set_git_user.sh

install: true

script:
    - cat /home/travis/build.sh
    - pwd
    - env
    - export IS_RELEASE=`git log -1 --pretty=%s | grep "\[maven-release-plugin\] prepare release"`
    - echo "$IS_RELEASE"
    -
        if [ -z "$TRAVIS_TAG" -a -z "$IS_RELEASE" ]; then
            if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
                $_MVN clean install;
                export DEPLOY_SITE=1;
            else
                $_MVN clean verify;
            fi
        fi
    - if [ -n "$DEPLOY_SITE" ]; then $_MVN site-deploy; fi

env:
    global:
        - _MVN='mvn -B -V -e -s ../settings.xml'

cache:
  directories:
  - $HOME/.m2

