sudo: false
language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

install:
    - mkdir -p ../utils
    - curl -Ls https://github.com/s4u/travis/archive/master.tar.gz \
      | tar -zx --strip-components 2 -C ../utils travis-master/src


script:
    - ../utils/mvn-push.sh clean install # execute on push
    - ../utils/mvn-pr.sh   clean verify  # execute on PR


