language: java
jdk:
  - oraclejdk8

env:
    global:
        - _MVN='mvn -B -V'

cache:
    directories:
        - $HOME/.m2

install: true

script:
    - export LAST_COMMIT_MSG=`git log -1 --pretty=%s`
    - env
    - if [ -n "$TRAVIS_TAG" ]; then exit 0; fi
    - $_MVN clean verify

