language: java
jdk:
  - oraclejdk8

env:
    global:
        - _MVN='mvn -B -V'

install: true

script:
    - export LAST_COMMIT_MSG=`git log -1 --pretty=%s`
    - 
        env; 
        cat ~/.m2/settings.xml; 
        if [ -z "$TRAVIS_TAG" ]; then 
            $_MVN clean verify; 
        fi
