language: java
jdk:
  - oraclejdk8

install: true

script:
    -
        if [ -z "$TRAVIS_TAG" ]; then
            if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
                $_MVN clean install;
            else
                $_MVN clean verify;
            fi
        fi

env:
    global:
        - _MVN='mvn -B -V -e'
