name: Java CI

on: [push, pull_request]

jobs:
  build-jdk-1_8:
 
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout 
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: mvn -B -V clean install
    - name: env
      run: env
